services:
  - postgresql

before_script:
  - psql -c "create user shiriux with password '4091';" -U postgres
  - psql -c 'create database shiriux_development;' -U postgres

language: ruby
rvm:
 - 2.2

